export const ELEMENTS_ACOESEMMASSA = {
    btnIniciar: '[ga-event="mktzap_bt_action_attendance_batch_close_start"]',
    btnFiltrar: '[ga-event="mktzap_bt_action_attendance_batch_close_new_filter"]',
    selecionarAcao: '[ga-event="mktzap_select_action_attendance_batch_close_new_action"]',
    acaoFinalizacaoAtendimentos: '1',
    acaoTransferenciaDeSetor: '2',
    acaoTransferenciaDeResponsável: '3',
    acaoClassificacaoDeAtendimentos: '4',
    selecionarStatusFinalizacao: '[ga-event="mktzap_select_action_attendance_batch_close_new_finalizationstatus"]',
    statusFinalizacao: '68',
    selecionarSetor: '[ng-model="vmBatchCloseNewCtrl.queue.sector_id"]',
    novoSetor: '62',
    selecionarResponsavel: '[ga-event="mktzap_select_action_attendance_batch_close_new_responsible"]',
    novoResponsavel: '113',
    selecionarClassificacao: '[ga-event="mktzap_select_action_attendance_batch_close_new_status_classification"]',
    novaClassificacao: '38',
    btnSelecionarTodos: '[for="select-all-histories"]',
    btnSelecionarUmPorUm: '[ga-event="mktzap_checkbox_action_attendance_batch_close_new_history"]',
    btnIniciarAcaoEmMassa: '[ga-event="mktzap_bt_action_attendance_batch_close_new_startbatch"]',
    selecionarFiltroSetor: '[ng-model="vmBatchCloseNewCtrl.queue.filters.sector_id"]',
    filtroSetor: 'number:1',
    selecionarFiltroClassificacao: '[ng-model="vmBatchCloseNewCtrl.queue.filters.status_id"]',
    filtroClassificacao: '38',
    selecionarFiltroCanalEntrada: '[ng-model="vmBatchCloseNewCtrl.queue.filters.channel"]',
    filtroCanalEntrada: 'string:Whatsapp',
    selecionarFiltroAutomatico: '[ng-model="vmBatchCloseNewCtrl.queue.filters.is_auto"]',
    filtroAutomatico: 'true',
}