export const ELEMENTS_ATIVO = {
    botaoEnvioAtivo: '#dropdownMenuLink',
    botaoAtivoWhats: '[ng-show="!vm.waitingActiveModal"]',
    botaoAtivoEmail: '[ga-event="mktzap_bt_action_att_active_email"]',
    canalEnvioWhats: '#activeChannel',
    telefoneWhats: '[ng-model="activeVm.activeWhatsapp.phone_number"]',
    telefoneTextoWhats: '14991895459',
    campoMensagemWhats: '#activeMessage',
    textoMensagem: 'Testes cypress envio ativo operador',
    criarAtivo: '[ga-event="mktzap_bt_action_attendance_modal_newwpp_modal_create"]',
    spanMensagemSucesso: '[data-test="toast-span-message"]',
    responsavel: '#responsible',
    campoHsm: '#activeHsmModel',
    fileInputElement: 'input[name=file]',
    arquivos: 'time.png',
    emailRemetente: '[ga-event="mktzap_bt_action_attendance_modal_newemail_modal_select"]',
    nomeDestinatario: '[ng-model="vm.activeEmail[vm.sector_id].name"]',
    emailDestinatario: '[ng-model="vm.activeEmail[vm.sector_id].to"]',
    nomeDestinatarioTexto: 'Sandra Pavan',
    emailDestinatarioTexto: 'sandra.pavan@gruponewway.com.br',
    assuntoDestinatario: '[ng-model="vm.activeEmail[vm.sector_id].subject"]',
    assuntoDestinatarioTexto: 'teste cypress email',
    criarAtivoEmail: '[ga-event="mktzap_bt_action_attendance_modal_newemail_modal_create"]',
    campoMensagemOperador: '#fieldMessage',
    mensagemOperador: 'Testes Cypress',
    enviarMensagem: '[ga-event="mktzap_bt_action_attendance_modal_send_message"]',
    conversaOperador: '[ng-repeat="message in vm.messages[vm.sector_id]"]',
    botaoAtivoSms: '[data-test="attendances-button-send_sms_active"]',
    canalEnvioSms: '[ng-model="vm.activeSMS.channel_id"]',
    telefoneSms: '[ng-model="vm.activeSMS.phone_number"]',
    telefoneTextoSms: '14991895459',
    campoMensagemSms: '#message',
    criarAtivoSms: '[ga-event="mktzap_bt_action_attendance_modal_newsms_modal_create"]',
    canalWhats: 'string:waweb_30',
    canalEnterprise: 'string:waent_6',
    hsmEnterprise: 'number:4',
    canalSms: 'number:19',
    canalEmail: '10'
}
