export const  ELEMENTS_CONTATO = {
    acessaContato: '[data-test="menu-a-contacts"]',
    acessaLista: '[data-test="menu-a-contacts_person"]',
    campoBusca: '#contactlist_fldSearchTerm',
    botaoBuscar: '#contactlist_btnSearchContact',
    botaoAcoes: '[ga-event="mktzap_bt_dropdown_contact"]',
    botaoEnviar: '[ga-event="mktzap_bt_active_contact"]',
    contatoBusca: '5514991895459',
    botaoEditar: '[ga-event="mktzap_bt_edit_contact"]',
    campoNome: '#contact_fldName',
    botaoSalvar: '#contact_btnSaveContact',
    botaoCancelar: '#contact_btnCancelContactEdit',
    modal: '#personEdit',
    botaoDetalhe:'[ga-event="mktzap_bt_view_contact"]',
    textoCampoNome: 'Isaac',
}
