export const ELEMENTS_MENU = {
    btnCanaisEntrada: ".QT-link-menu-channels",
    btnCanaisEntradaAutoNegociador: '[data-test="menu-a-channels_negotiator"]',
    btnCanaisEntradaEmail: '[data-test="menu-a-channels_emails"]',
    btnCanaisEntradaFacebook: '[data-test="menu-a-channels_emails"]',
    btnCanaisEntradaInstagram: '[data-test="menu-a-channels_instagram"]',
    btnCanaisEntradaMulticanalidade: '[data-test="menu-a-channels_multichannel"]',
    btnCanaisEntradaNewChat: '[ga-event="mktzap_bt_action_newchat_menu"]',
    btnCanaisEntradaSmartChannel: '[data-test="menu-a-channels_smart"]',
    btnCanaisEntradaSms: '[data-test="menu-a-channels_sms"]',
    btnCanaisEntradaTelegram: '[ga-event="mktzap_bt_action_telegram_menu"]',
    btnCanaisEntradaWebChat: '[data-test="menu-a-channels_webchat"]',
    btnCanaisEntradaWhatsapp: '[data-test="menu-a-channels_whatsapp"]',
    btnCanaisEntradaWaent: '[data-test="menu-a-channels_waent"]',
}