//URL de acesso
export const ELEMENTS_BASE_URL = {
    baseUrl: 'https://qa-poli.infranw.com.br/login',
    baseUrlLord: 'https://qa-poli.infranw.com.br/wolologin',
    baseUrlLogado:'https://qa-poli.infranw.com.br/chat',
    baseUrlLogout: 'https://qa-poli.infranw.com.br/login',
    baseUrlMaling: 'https://qa-poli.infranw.com.br/mailing-list',
    baseUrlCampanha: 'https://qa-poli.infranw.com.br/campaign-list',
    baseUrlRelatorioAnalitico : 'https://qa-poli.infranw.com.br/reports/analytic',
    baseUrlRelatorioEfetividade:'https://qa-poli.infranw.com.br/reports/effectiviness',
    baseUrlRelatorioEnquete: 'https://qa-poli.infranw.com.br/reports/polls',
    baseUrlRelatorioCompleto:'https://qa-poli.infranw.com.br/report-bi/report-complete#',
    baseUrlRelatorioProdutividade: 'https://qa-poli.infranw.com.br/reports/productivity',
    baseUrlRelatorioGatilho: 'https://qa-poli.infranw.com.br/reports/trigger',
    baseUrlRelatorioPausa: 'https://qa-poli.infranw.com.br/reports/pause-control#menu-report',
    baseUrlRelatorioSessao: 'https://qa-poli.infranw.com.br/reports/session-control',
    baseUrlRelatorioAtivo: 'https://qa-poli.infranw.com.br/reports/active',
    baseUrlRelatorioOptin: 'https://qa-poli.infranw.com.br/reports/optin',
    baseUrlNewEnquete: 'https://qa-poli.infranw.com.br/polls',
    baseUrlNewStatus: 'https://qa-poli.infranw.com.br/status',
    baseUrlHistorico: 'https://qa-poli.infranw.com.br/history',
    baseUrlAlertaInterno: 'https://qa-poli.infranw.com.br/internal-messenger',
    baseUrlPerguntaseRespostas: 'https://qa-poli.infranw.com.br/knowledge-base',
    baseUrlConfiguracoes: 'https://qa-poli.infranw.com.br/company#',
    baseUrlDashMonitoria: 'https://qa-poli.infranw.com.br/dashboard/distribution-monitoring',
    baseUrlGestaoNegocio: 'https://qa-poli.infranw.com.br/dashboard/dashboard-business-management',
    baseUrlDashGestaoEquipe: 'https://qa-poli.infranw.com.br/dashboard/dashboard-team-management',
    baseUrlResumoOperacional: 'https://qa-poli.infranw.com.br/dashboard/dashboard-operational-summary',
    baseUrlComunicacaoInterna: 'https://qa-poli.infranw.com.br/dashboard/dashboard-internal-communication',
    baseUrlHoraaHora: 'https://qa-poli.infranw.com.br/reports/every-hour',
    baseUrlNewchat: 'https://qa-poli.infranw.com.br/newchat#',
    baseUrlPainel: 'https://qa-poli.infranw.com.br/chat',
    baseUrlAtendimento: 'https://qa-poli.infranw.com.br/chat#menu-attendance',
    baseUrlDistribuicao: 'https://qa-poli.infranw.com.br/rules/attendances/automatic-distribution',
    baseUrlRelatorioBackground: 'https://qa-poli.infranw.com.br/general-settings/settings',
    baseUrlConfigsGerais: 'https://qa-poli.infranw.com.br/general-settings/settings#config',
    baseUrlAcoesEmMassa: 'https://qa-poli.infranw.com.br/batch-close',
    baseUrlCanaisEntradaSms: 'https://qa-poli.infranw.com.br/sms'
}
